"""Pure generated-file / length detection for the length-gate hook.

Single source of truth for `length-quality-note.py`. Importable so the
counting and AST logic are unit-testable independent of the hook payload
plumbing (mirrors the `_markers.py` shared-detector-module pattern). Stdlib
only.

Design (decision-reviewer + advisor, 2026-07-06): no before/after size
comparison -- flag any over-threshold file/function on the current content
alone; ticket-discipline (`_hooklib.tickets_mentioning`), not a delta split,
is the noise-reduction mechanism. Qualnames are built via a recursive
NodeVisitor (push/pop per scope) -- `ast.walk` is breadth-first with no
ancestor context and cannot do this.
"""

import ast
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _hooklib import CODE_EXTENSIONS

# SQL migrations/schema dumps and Vue/Svelte SFCs (template+script+style
# bundled in one file) legitimately exceed 400 lines for reasons unrelated to
# hand-written imperative-logic bulk, which is the rule's intent. Carved out
# of the file-length check only; function-length stays Python-only regardless.
FILE_LENGTH_EXTENSIONS = CODE_EXTENSIONS - {".sql", ".vue", ".svelte"}

FILE_LENGTH_THRESHOLD = 400
FUNCTION_LENGTH_THRESHOLD = 60
GENERATED_HEADER_LINES = 20
_GENERATED_COMMENT_PREFIXES = (
    "<!--", '"""', "'''", "//", "/*", "-- ", "*", "# ", "##", ";",
)
_GENERATED_COMMENT_BLOCKS = (
    ('"""', '"""'),
    ("'''", "'''"),
    ("/*", "*/"),
)
_GENERATED_DECLARATION_PREFIXES = (
    "@generated",
    "generated by",
    "generated from",
    "code generated by",
    "auto-generated by",
    "autogenerated by",
    "automatically generated by",
    "generated automatically by",
    "auto-generated file",
    "autogenerated file",
    "automatically generated file",
    "this file is generated",
    "this file was generated",
    "this file is auto-generated",
    "this file was auto-generated",
    "this file is autogenerated",
    "this file was autogenerated",
    "this file is automatically generated",
    "this file was automatically generated",
    "this code is generated",
    "this code was generated",
    "this is a generated file",
    "this is an auto-generated file",
    "this is an autogenerated file",
)


def count_lines(text):
    """Line count matching editor display (`str.splitlines`), not `wc -l`
    (which undercounts a file lacking a trailing newline by one)."""
    return len(text.splitlines())


def _comment_metadata(line):
    stripped = line.lstrip().casefold()
    matched = False
    while True:
        for prefix in _GENERATED_COMMENT_PREFIXES:
            if stripped.startswith(prefix):
                stripped = stripped[len(prefix):].lstrip()
                matched = True
                break
        else:
            return stripped if matched else None


def _declares_machine_generated(metadata):
    if metadata.startswith(_GENERATED_DECLARATION_PREFIXES):
        return True
    return (metadata.startswith("do not edit")
            and "generated" in metadata
            and ("file" in metadata or "code" in metadata))


def _unclosed_comment_block(line):
    stripped = line.lstrip()
    for opener, closer in _GENERATED_COMMENT_BLOCKS:
        if stripped.startswith(opener):
            remainder = stripped[len(opener):]
            return closer if closer not in remainder else None
    return None


def is_machine_generated(text):
    """True when comment metadata in the bounded header declares generated code.

    Declaration-specific wording avoids treating generator descriptions or
    source strings as claims that the generator itself is machine-maintained.
    """
    block_closer = None
    for line in text.splitlines()[:GENERATED_HEADER_LINES]:
        if block_closer is not None:
            content, found_closer, _remainder = line.partition(block_closer)
            metadata = _comment_metadata(content)
            metadata = content.strip().casefold() if metadata is None else metadata
            if _declares_machine_generated(metadata):
                return True
            if found_closer:
                block_closer = None
            continue
        metadata = _comment_metadata(line)
        if metadata is not None and _declares_machine_generated(metadata):
            return True
        block_closer = _unclosed_comment_block(line)
    return False


class _FunctionSpanVisitor(ast.NodeVisitor):
    def __init__(self):
        self.stack = []
        self.spans = []

    def _visit_scope(self, node):
        self.stack.append(node.name)
        self.generic_visit(node)
        self.stack.pop()

    def visit_ClassDef(self, node):
        self._visit_scope(node)

    def visit_FunctionDef(self, node):
        self.spans.append((".".join(self.stack + [node.name]),
                           node.lineno, node.end_lineno))
        self._visit_scope(node)

    def visit_AsyncFunctionDef(self, node):
        self.spans.append((".".join(self.stack + [node.name]),
                           node.lineno, node.end_lineno))
        self._visit_scope(node)


def python_function_spans(text):
    """(qualname, start_lineno, end_lineno) for every function/method in
    `text`, dotted by enclosing class/function nesting. Raises SyntaxError on
    malformed Python -- callers must catch it and skip the function-length
    check (file-length still applies, since it needs no parse)."""
    tree = ast.parse(text)
    visitor = _FunctionSpanVisitor()
    visitor.visit(tree)
    return visitor.spans


def over_threshold_functions(text, threshold=FUNCTION_LENGTH_THRESHOLD):
    """[(qualname, start, end, length), ...] for functions strictly over
    `threshold` lines. Raises SyntaxError on malformed Python (caller catches)."""
    result = []
    for qualname, start, end in python_function_spans(text):
        length = end - start + 1
        if length > threshold:
            result.append((qualname, start, end, length))
    return result
