package main

var registeredCommands = []commandSpec{
	{
		ID: "tui.open", Usage: "mainframe",
		Summary:       "Open the terminal interface.",
		Input:         inputTerminal,
		Output:        outputTerminal,
		Effect:        effectReviewedWrite,
		Confirmation:  confirmationTerminal,
		Documentation: "overview",
		HandlerKind:   handlerTUI,
	},
	{
		ID: "plan", Pattern: []string{"plan"},
		Usage:         "mainframe plan",
		Summary:       "Build a read-only installation plan from JSON on standard input.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "agent-automation",
		HandlerKind:   handlerPlan,
	},
	{
		ID: "draft.review", Pattern: []string{"draft", "review"},
		Usage:         "mainframe draft review",
		Summary:       "Review a complete desired adapter and MCP draft without applying it.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "agent-automation",
		HandlerKind:   handlerDraftReview,
	},
	{
		ID: "draft.apply",
		Pattern: []string{
			"draft", "apply", "--confirm", "<digest>",
		},
		Usage:         "mainframe draft apply --confirm <digest>",
		Summary:       "Apply the exact applicable adapter and MCP draft returned by review.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReviewedWrite,
		Confirmation:  confirmationDigest,
		Documentation: "agent-automation",
		HandlerKind:   handlerDraftApply,
	},
	{
		ID: "credentials.catalog", Pattern: []string{"credentials"},
		Usage:         "mainframe credentials",
		Summary:       "List credential definitions and user-owned instances without values.",
		Input:         inputNone,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialList,
	},
	{
		ID: "credentials.uses", Pattern: []string{"credentials", "uses", "<name>"},
		Usage:         "mainframe credentials uses <name>",
		Summary:       "List credential-instance roles that reference one secret name.",
		Input:         inputArguments,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialUses,
	},
	{
		ID:            "credentials.legacy-indexes",
		Pattern:       []string{"credentials", "legacy-indexes"},
		Usage:         "mainframe credentials legacy-indexes",
		Summary:       "Inspect legacy credential locations without returning their content.",
		Input:         inputNone,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialLegacy,
	},
	{
		ID:            "credentials.legacy-preview",
		Pattern:       []string{"credentials", "legacy-preview"},
		Usage:         "mainframe credentials legacy-preview",
		Summary:       "Discover named references in the shared legacy catalog without writing.",
		Input:         inputNone,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialLegacyPreview,
	},
	{
		ID:            "credentials.legacy-plan",
		Pattern:       []string{"credentials", "legacy-plan"},
		Usage:         "mainframe credentials legacy-plan",
		Summary:       "Build a read-only transfer plan for all classified legacy catalogs.",
		Input:         inputNone,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialLegacyPlan,
	},
	{
		ID:            "credentials.legacy-review",
		Pattern:       []string{"credentials", "legacy-review"},
		Usage:         "mainframe credentials legacy-review",
		Summary:       "Review legacy transfer choices without writing.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialLegacyReview,
	},
	{
		ID: "credentials.legacy-apply",
		Pattern: []string{
			"credentials", "legacy-apply", "--confirm", "<digest>",
		},
		Usage:         "mainframe credentials legacy-apply --confirm <digest>",
		Summary:       "Apply the exact complete legacy transfer returned by review.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReviewedWrite,
		Confirmation:  confirmationDigest,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialLegacyApply,
	},
	{
		ID:            "credentials.instance.review",
		Pattern:       []string{"credentials", "instance", "review"},
		Usage:         "mainframe credentials instance review",
		Summary:       "Review a credential-instance create or edit request.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialReview,
	},
	{
		ID: "credentials.instance.apply",
		Pattern: []string{
			"credentials", "instance", "apply", "--confirm", "<digest>",
		},
		Usage:         "mainframe credentials instance apply --confirm <digest>",
		Summary:       "Apply the exact credential-instance change returned by review.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReviewedWrite,
		Confirmation:  confirmationDigest,
		Documentation: "credentials",
		HandlerKind:   handlerCredentialApply,
	},
	{
		ID:            "release.review",
		Pattern:       []string{"release", "review"},
		Usage:         "mainframe release review",
		Summary:       "Review a local release import or exact cached activation.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "releases",
		HandlerKind:   handlerReleaseReview,
	},
	{
		ID: "release.apply",
		Pattern: []string{
			"release", "apply", "--confirm", "<digest>",
		},
		Usage:         "mainframe release apply --confirm <digest>",
		Summary:       "Apply the exact launcher activation returned by release review.",
		Input:         inputJSON,
		Output:        outputJSON,
		Effect:        effectReviewedWrite,
		Confirmation:  confirmationDigest,
		Documentation: "releases",
		HandlerKind:   handlerReleaseApply,
	},
	{
		ID: "docs.list", Pattern: []string{"docs", "list"},
		Usage:         "mainframe docs list",
		Summary:       "List documentation embedded in this executable.",
		Input:         inputNone,
		Output:        outputText,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "overview",
		HandlerKind:   handlerDocsList,
	},
	{
		ID: "docs.show", Pattern: []string{"docs", "show", "<topic>"},
		Usage:         "mainframe docs show <topic>",
		Summary:       "Print one embedded documentation topic.",
		Input:         inputArguments,
		Output:        outputText,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "overview",
		HandlerKind:   handlerDocsShow,
	},
	{
		ID: "capabilities", Pattern: []string{"capabilities", "--json"},
		Usage:         "mainframe capabilities --json",
		Summary:       "Describe the installed command and documentation contract for agents.",
		Input:         inputNone,
		Output:        outputJSON,
		Effect:        effectReadOnly,
		Confirmation:  confirmationNone,
		Documentation: "agent-automation",
		HandlerKind:   handlerCapabilities,
	},
}
